### PR TITLE
Improvement: import is now very error tolerant

### PR DESCRIPTION
**Pull request by mamuesp**
No more need of "begin" or "end" comments - just throw the data in. It searches for keywords (aka node types) at the start of each line and tries to parse these lines.

And yes, the data is completely in the "index.html" file, the resource-folder is obsolete (I forgot to delete it ...) I'm not so happy about this matter because this is a huge amount of data hold as global variables, but the offline paradigm rules. So I can live with that ... ;-)

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
did this fully resolve issue #129

**Comment by mamuesp** [comment]
Yes, but without the reference to #59. You may now just throw a full Arduino sketch in the textpanel, and the parser just picks the lines it understands. For the moment I'm looking for a possibility to automatically place the nodes without stacking them (on base of D3 funxtionality like shown [here](http://vowl.visualdataweb.org/webvowl/) or [there](http://bl.ocks.org/MoritzStefaner/1377729)) in one pile when there are no coordinates, after this issue I will look into #59 and affected issues.

**Comment by mamuesp** [comment]
to be a little more discreet, I tried to use the PM channel in the forum ... but this opportunity is blocked ...

Just as information - the tool version online is one with the bug which kills the import function ("count" is not defined) ... perhaps you might install an update.

Regards,
Manfred

**Comment by PaulStoffregen** [comment]
Website updated

**Pull request merged**
