### PR TITLE
SPDIF3, initial cache-support

### PR DESCRIPTION
**Pull request by FrankBoesing**

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Is this ready to merge?

**Comment by FrankBoesing** [comment]
yes it is.
Right now I'm having troublewith TDM - I was about to start with the  TDM-input - but the cs42448 does not seem to respond to I2C anymore - however, with a T3.2 it still works. Likely a hardware-issue on my side - or  has something in wire.h changed?

Am 27. Februar 2019 01:24:03 MEZ schrieb Paul Stoffregen <notifications@github.com>:
>Is this ready to merge?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/Audio/pull/289#issuecomment-467671226

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by PaulStoffregen** [comment]
I have one more untested CS42448 board here.  Let me know if you need it?

**Comment by FrankBoesing** [comment]
Thank, it was a broken dupont..

**Pull request merged**
