### PR TITLE
Added a drum synthesis object to Audio library

### PR DESCRIPTION
**Pull request by Jacquot-SFE**
Hello Paul,

I've got a number of audio library objects I'd like to contribute.  I'm starting with the simplest one, a DDS-based drum class.

I think everything should be in order - working atop the latest baseline, MIT license in place, a functional sketch example, and the HTML file updated.

If I've missed something, please let me know.

Thanks!

### CODE REVIEW

**Comment by mihow** [comment]
This is great. I look forward to testing!

**Comment by PaulStoffregen** [comment]
This looks really awesome. Sorry I haven't had time to review it yet. I'm crazy busy with the Prop Shield beta at this moment.  I probably won't be able to merge this (or even really look at it) for several days. But I won't forget... if you don't hear by next week, please ping me.

**Comment by Pensive** [comment]
This looks awesome; I can't wait to have a play. Perhaps we should try and incorporate some presets in the future for 808, Roland Compurhythm etc. This could have some legs!!!!!

I'm thinking of changing my Beats by Teensy to a step sequencer instead, this would expand the drum options immensely.

Thanks Jacquot-SFE!

**Comment by Jacquot-SFE** [comment]
Howdy Paul,

As you requested, a friendly reminder to take a look at this pull.

Thanks!

**Comment by PaulStoffregen** [comment]
Oh, sorry this has sat for so very long.  I'm going to merge it now.  Eventually I do believe we'll need to consider naming conventions and common APIs for musical instrument synth objects, but the last thing I want to do right now is hold this up any longer.

**Pull request merged**
