### PR TITLE
way faster 32 bit memcpy

### PR DESCRIPTION
**Pull request by FrankBoesing**
32 bit memoryaccess, 32 bit addition, unrolled loop

### CODE REVIEW

**Comment by FrankBoesing** [comment]
I'll make an assembler version instead.

**Comment by PaulStoffregen** [comment]
Eventually, I would like to change the PDB to default to 4X the sample rate and bring the oversampling code from PT2811 into the DAC objects.  On the ADC side, simply averaging 4 samples together would be ok.  Eventually, I want to try a small FIR filter on 4X oversampled ADC input.

Any thoughts or ideas on this?  At the very least, it will require a different memory copy, right?

**Comment by FrankBoesing** [comment]
Hi Paul,

please take a look here : 
https://github.com/PaulStoffregen/Audio/blob/master/output_pt8211.cpp#L130
Currently, a memcpy is only used without interpolation.

Some thoughts:

That time Ben wrote this code, I spent some time with trying to optimize 
it - but i could not find a good way. A little bit can be made better 
with unrolling the x4 loop (line 154+) or, maybe, with trying to move 
the conditional out of the loop.

On the other hand, we only need 12 bit, so there might be a way. The 
values used in that code are all 32BIT to minimize errors. With 12BIT 
values this might not be needed and we can use 16 BIT variables instead...

After that, one could try to translate the new code to assembler...



Am 22.04.2017 um 19:33 schrieb Paul Stoffregen:

**Comment by FrankBoesing** [comment]
Hi Paul,

you got me ;-) I have a now working version with 4x oversampling.
There are some questions left..

a) is it ok to create globale define "AUDIO_OUTPUT_OVERSAMPLING" (just 
like AUDIO_BLOCK_SAMPLES)
- this way we can use it for PT8211, too, and it is more clear to the 
user how to use it.

b) isn't the ADC using the same PDB ?

**Comment by FrankBoesing** [comment]
Paul, the compiler makes a pretty good job for the oversampling-code (at least with "mono").
I'll make a fork with all my changes later today - but I'd like that you take a look at the sourcecode before I invest more work on it (-> stereoDACs). 
Then, I'm unsure what to do with the ADCs. Can you make the neccessary changes for the ADCs?

**Pull request closed without merging**
