### PR TITLE
Memcpy quad

### PR DESCRIPTION
**Pull request by FrankBoesing**

### CODE REVIEW

**Comment by FrankBoesing** [comment]
...something is wrong with my repositories. sry...

call it like this : memcpy_tointerleaveQuad((int16_t*) dest, (int16_t*)src1, (int16_t*)src2, (int16_t*)src3, (int16_t*)src4);

i think i have to delete my copy and re-fork(?)

**Comment by FrankBoesing** [comment]
p.s. speed up is 2x

**Comment by PaulStoffregen** [comment]
Thanks.

manually merged https://github.com/PaulStoffregen/Audio/commit/36481730b68c291a1d0204206d436959cc61434e

**Comment by PaulStoffregen** [comment]
Yeah, so much has changed recently... best to update or just re-fork.

**Pull request closed without merging**
