### PR TITLE
add on-click message

### PR DESCRIPTION
**Pull request by FrankBoesing**

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
Using it now.  The notification messages look good.

Also committed a fix for I2S slave output.

**Comment by PaulStoffregen** [comment]
Looks like there's a bug when reloading the page, where 1 of the conflicting objects doesn't get the icon.  But clicking it or the conflicting on causes it to appear.

**Comment by FrankBoesing** [comment]
Yes, I mentioned that in the last PR. At the moment, I don't know how to fix that.

**Comment by FrankBoesing** [comment]
Normally, you don't click "reload".
An then, the missing icon appears if you click anywhere (not only  a node).
So that's a very minor issue.

**Comment by FrankBoesing** [comment]
The updated CSS file is missing on the website, Paul :)

**Pull request merged**
