### PR TITLE
one more fix

### PR DESCRIPTION
**Pull request by FrankBoesing**
ok, the previous issue is now fixed, too.

There is one very minor issue remaining:
If you click "reload"" the first node gets no error-icon.
With the fist click to the workspace it reappears.
I'll do not fix that now.
Maybe one day.

### CODE REVIEW

**Comment by FrankBoesing** [comment]
I think we're done with that now.

**Comment by PaulStoffregen** [comment]
Wish I could try this right now, but need to wait until tonight.  We're crazy busy here just trying to keep the company running today.

**Comment by FrankBoesing** [comment]
No Problem - keep care.

**Comment by PaulStoffregen** [comment]
Running it now.  Looks really good.  :)

Now it's much easier to tell which objects conflict, because the icon appears immediately on the others when you add the conflicting one.  Very nice.

The next step is the make those icons clickable.  I do not know which GUI way is best to show a message.  Maybe a dialog box?  Or maybe the drop-down panel which is used for other errors?  Or maybe a floating message?  Any ideas?

**Comment by FrankBoesing** [comment]
Not sure what the easiest is.
Didn't look that much at the code.
I from the look&feel I'd prefer a floating message on mouseover.

I can add this, maybe - but not today. I'm busy.. :(


Am 29. Mai 2020 11:01:01 MESZ schrieb Paul Stoffregen <notifications@github.com>:
>Running it now.  Looks really good.  :)
>
>Now it's much easier to tell which objects conflict, because the icon
>appears immediately on the others when you add the conflicting one. 
>Very nice.
>
>The next step is the make those icons clickable.  I do not know which
>GUI way is best to show a message.  Maybe a dialog box?  Or maybe the
>drop-down panel which is used for other errors?  Or maybe a floating
>message?  Any ideas?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PaulStoffregen/Audio/pull/348#issuecomment-635860378

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
