### PR TITLE
add input_i2s2, keywords,

### PR DESCRIPTION
**Pull request by FrankBoesing**
+ a little cleanup

### CODE REVIEW

**Comment by FrankBoesing** [comment]
nope.. i make a new tomorrow.

**Comment by PaulStoffregen** [comment]
ok, so I can ignore this one?

**Comment by FrankBoesing** [comment]
yes, I'll create a new one this evening, with TDM (at least output for SAI1). More to come this weekend.

**Comment by jshoek** [comment]
I should probably know this by now but when updates are made like this, am I suppose to down load each file listed in the post and place them the library folders or is there an easier way to include all files?

**Comment by PaulStoffregen** [comment]
Yes, to get the very latest you need to pull from github.

Every few weeks I package up an installer with everything that's been merged.  So if you can wait a little while, the installer is the simplest way.

https://forum.pjrc.com/threads/54711-Teensy-4-0-First-Beta-Test?p=193715&viewfull=1#post193715

**Comment by jshoek** [comment]
I'm assuming with these software updates that they are appropriate for all the 3.x boards.

**Comment by FrankBoesing** [comment]
they are not needed for 3.x boards. they are useful for the teensy-4 only.

**Pull request closed without merging**
