### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by ivankravets**
Hi @PaulStoffregen,

I see that your project contains the practical examples. All of us understand that it’s not easy to test them before each new commit to this repository. What is more, need to be sure that all of these examples are actual and compile without errors.

I propose to solve this task using [Continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) practice which is intended to detect [integration bugs](https://en.wikipedia.org/wiki/Software_testing#Integration_testing) and save time over the lifespan of a project.

## How does it work?
The each new commit to this repository will be tested using existing examples with appropriate platforms/embedded boards. @PlatformIO is used here as cross-platform code builder and library manager in pair with @travis-ci (distributed continuous integration service). 

## Quickstart
Please enable @travis-ci following the steps 1, 2 and 5 here http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A 

For more details please follow to:

* Official Travis CI Documentation for PlatformIO: https://docs.travis-ci.com/user/integration/platformio/
* PlatformIO documentation for Travis CI: http://docs.platformio.org/en/latest/ci/travis.html

## Status Badge
You can add [badge with build status](https://docs.travis-ci.com/user/status-images/) to your README

**Markdown**
```
[![Build Status](https://travis-ci.org/PaulStoffregen/Audio.svg?branch=master)](https://travis-ci.org/PaulStoffregen/Audio)
```

**RST**
```
.. image:: https://travis-ci.org/PaulStoffregen/Audio.svg?branch=master
    :target: https://travis-ci.org/PaulStoffregen/Audio
```

## Examples

* Project [USB_Host_Shield_2.0](https://github.com/felis/USB_Host_Shield_2.0) [Build Status](https://travis-ci.org/felis/USB_Host_Shield_2.0)
* Project [Arduino-IRremote](https://github.com/z3t0/Arduino-IRremote) [Build Status](https://travis-ci.org/z3t0/Arduino-IRremote)
* Project [ethercard](https://github.com/jcw/ethercard) [Build Status](https://travis-ci.org/jcw/ethercard)

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
I'm not familiar with how this works.

But I can tell you all the part 2 and 3 tutorials intentionally DO NOT compile as-is.  The tutorials are designed for the user to perform work with the design tool to copy additional code before compiling.

Will listing them in this file cause a false alarm.

**Comment by ivankravets** [comment]
You have made a lot of job here. Need to understand which examples require additional libraries/configs. I'll tune this `.travis.yml` after your enable Travis CI for this project. 

Please complete "Quickstart" section. Thanks in advance!

P.S: This is test/experimental PR with Continuos Integration. I don't know how other developers will react on me :( However, I'll try to explain and help each developer.

**Comment by PaulStoffregen** [comment]
ok, I've done all the steps, but I really don't have any more time for this.

**Comment by ivankravets** [comment]
Thanks,I see! It's enough for me. I'll fork your repo with this config and test all these things. If I'll have any changes, like badge for README and etc., I will propose all in the one PR.

Thanks a lot!

**Comment by mihow** [comment]
Wow I had no idea TravisCL could be used for embedded platforms. Curious to
see where this goes Ivan.

**Comment by PaulStoffregen** [comment]
Looks like platformio isn't linking the arm math library, which causes the build to fail.

Here's how it happens in Arduino:

armmath

**Pull request merged**
